# my_app_config/values.yaml
# Cấu hình cho môi trường lab

backend:
  replicaCount: 1
  image:
    # CI pipeline sẽ tự động cập nhật tag này
    tag: "v1.0.0" 

frontend:
  replicaCount: 1
  image:
    tag: "v1.0.0"

database:
  password: "123" # Mật khẩu bạn đã dùng trong docker-compose